# Generated by Django 5.1.7 on 2025-03-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='Middle', max_length=50),
        ),
    ]
