# Generated by Django 5.1.7 on 2025-04-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_task_user_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
